# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'gopenpgp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gopenpgp
  pod 'SwiftProtobuf', '~> 1.5.0'

  target 'gopenpgpTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'CryptoSwift', '~> 1.0.0'
  end

end

