// Objective-C API for talking to github.com/ProtonMail/gopenpgp/models Go package.
//   gobind -lang=objc github.com/ProtonMail/gopenpgp/models
//
// File is generated by gobind. Do not edit.

#ifndef __Models_H__
#define __Models_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class ModelsDecryptSignedVerify;
@class ModelsEncryptedSigned;
@class ModelsEncryptedSplit;

/**
 * DecryptSignedVerify contains a decrypted message and verification result.
 */
@interface ModelsDecryptSignedVerify : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * clear text
 */
@property (nonatomic) NSString* _Nonnull plaintext;
/**
 * bitmask verify status : 0
 */
@property (nonatomic) long verify;
/**
 * error message if verify failed
 */
@property (nonatomic) NSString* _Nonnull message;
@end

/**
 * EncryptedSigned contains an encrypted message and signature.
 */
@interface ModelsEncryptedSigned : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull encrypted;
@property (nonatomic) NSString* _Nonnull signature;
@end

/**
 * EncryptedSplit contains a separate session key packet and symmetrically
encrypted data packet.
 */
@interface ModelsEncryptedSplit : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable dataPacket;
@property (nonatomic) NSData* _Nullable keyPacket;
@property (nonatomic) NSString* _Nonnull algo;
@end

#endif
